name: Storefront
author: JCThePants
main: com.jcwhatever.bukkit.storefront.Storefront
version: 0.1-beta
depend: [NucleusFramework]
commands:
    storefront:
        aliases: [store, stores]
        description: Base command for Storefront
        usage: |
            ERROR!