name: Storefront
author: JCThePants
main: com.jcwhatever.bukkit.storefront.Storefront
version: 0.0-beta
depend: [GenericsLib]
commands:
    store:
        description: Base command for Storefront
        usage: |
            ERROR!
    stores:
        description: Base command for Storefront
        usage: |
            ERROR!